name: Nightly CI
on:
  # Runs every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Manual Dispatch
  workflow_dispatch:

jobs:
  check-commits:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tools: [pdk, OpenLane, caravel, precheck, mgmt_core_wrapper, caravel_user_project, caravel_aes_example]
    steps:
      - uses: actions/checkout@v3
      - name: Parse JSON file
        run: |
          python3 $GITHUB_WORKSPACE/.github/scripts/update_tool.py --json $GITHUB_WORKSPACE --tool ${{ matrix.tools }}

      - name: Create Pull Request
        if: ${{ env.NO_UPDATE != '1' }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MY_TOKEN }}
          title: "[BOT] Update ${{ matrix.tools }}"
          body: |
            This is an automated PR.

            See the individual commits for details.
          commit-message: |
            [BOT] Update ${{ matrix.tools }}
          branch: ${{ matrix.tools }}-update-branch
          delete-branch: true