name: Nightly CI
on:
  # Runs on Every Push
  push:
  # Runs on Pull Requests
  pull_request:
  workflow_dispatch:

jobs:
  check-commits:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tools: [pdk, OpenLane, caravel, precheck, mgmt_core_wrapper]
    steps:
      - uses: actions/checkout@v2
      - name: Parse JSON file
        run: |
          python3 $GITHUB_WORKSPACE/.github/scripts/update_tool.py --json $GITHUB_WORKSPACE/tools.json --tool ${{ matrix.tools }}

      - name: Create Pull Request
        if: ${{ env.NO_UPDATE != '1' }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "[BOT] Update ${{ env.TOOL }}"
          body: |
            This is an automated PR.

            See the individual commits for details.
          commit-message: |
            [BOT] Update ${{ matrix.tools }}
          branch: ${{ matrix.tools }}-update-branch
          push-to-fork: ${{ vars.FORK_NAME }}
          delete-branch: true