name: Nightly CI
on:
  # Runs on Every Push
  push:
  # Runs on Pull Requests
  pull_request:
  workflow_dispatch:

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Parse JSON file
        run: |
          echo "Parsing JSON file..."
          json_file=$(cat $GITHUB_WORKSPACE/tools.json)
          repos=$(echo $json_file | jq -r 'keys[]')
          for repo in $repos; do
            commit=$(echo $json_file | jq -r ".[$repo] | .commit")
            url=$(echo $json_file | jq -r ".[$repo] | .url")
            echo "Latest commit for $repo is $commit at $url"
          done

      - name: Get latest commits
        for repo in $repos; do
          latest_commit=$(curl -s $url/commits/master | jq -r '.[0].sha')
          echo "Latest commit for $repo is $latest_commit"
          echo "Updating JSON file..."
          json_file=$(jq ".[$repo] |= {commit: $latest_commit}" $json_file)
          echo $json_file > $GITHUB_WORKSPACE/tools.json
        done

      - name: Create PR
        uses: actions/github-pr@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Update JSON file with latest commits
          body: |
            Updates the JSON file with the latest commits from the following repos:
            $repos
          branch: update-json-file
          base: main